# Build GOLANG applications

variables:
  KANIKO_IMAGE: gcr.io/kaniko-project/executor:debug

stages:
  - deploy

go_deploy:
  stage: deploy
  only:
    - tags
  image:
    name: $KANIKO_IMAGE
    entrypoint: [""]
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
    IMAGE_TAG_LATEST: latest
    CONTAINER_IMAGE: $REGISTRY_HARBOR/library/workspaceone-exporter
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY_HARBOR\":{\"auth\":\"$(printf "%s:%s" "$REGISTRY_HARBOR_USER" "$REGISTRY_HARBOR_PASSWORD" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - echo "$PKI_ROOT_CA" >> /kaniko/ssl/certs/ca-certificates.crt
    - >
      if [ -n "$CI_COMMIT_TAG" ]; then
        IMAGE_TAG=$CI_COMMIT_TAG
      else
        IMAGE_TAG=`date '+%y.%m.%d-%H%M'`
      fi
  script:
    - >-
      /kaniko/executor
      --context="${CI_PROJECT_DIR}"
      --dockerfile="${CI_PROJECT_DIR}/Dockerfile"
      --destination="${CONTAINER_IMAGE}:${IMAGE_TAG}"
      --destination="${CONTAINER_IMAGE}:${IMAGE_TAG_LATEST}"
