apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workspaceone-exporter.fullname" . }}
  labels:
    {{- include "workspaceone-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "workspaceone-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "workspaceone-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "workspaceone-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WS1_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: workspaceone-token-secret
                  key: ws1UserToken
            - name: WS1_TENANT_KEY
              valueFrom:
                secretKeyRef:
                  name: workspaceone-token-secret
                  key: ws1ServerToken
            - name: WS1_URL
              value: {{ .Values.ws1Url | quote }}
            - name: WS1_LGID
              value: {{ .Values.ws1Lgid | quote }}
            - name: WS1_INTERVAL
              value: {{ .Values.ws1Interval | quote }}
            - name: TAG_FILTER
              value: {{ .Values.ws1TagFilter | quote }}
            - name: TAG_PARSING
              value: {{ .Values.ws1TagParsing | quote }}
            - name: INSECURE
              value: {{ .Values.ws1Insecure | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
