apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workspaceone-exporter
spec:
  endpoints:
  - honorLabels: true
    port: http
  jobLabel: workspaceone-exporter
  namespaceSelector:
    matchNames:
      - {{ template "workspaceone-exporter.namespace" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: workspaceone-exporter
